export const SEC_METRIC_KEYS = [
  "revenue",
  "net_income",
  "operating_income",
  "gross_profit",
  "operating_cash_flow",
  "capex_cash",
  "capex_incurred",
  "capex_unpaid",
  "income_tax_expense",
  "operating_expenses",
  "research_and_development_expense",
  "selling_general_and_administrative_expense",
  "cost_of_goods_sold",
  "depreciation_depletion_and_amortization",
  "interest_expense",
  "interest_income",
  "net_interest_nonoperating",
  "eps_basic",
  "eps_diluted",
  "weighted_avg_shares_basic",
  "weighted_avg_shares_diluted",
  "dividends_per_share",
  "dividend_payments",
  "share_repurchases",
  "investing_cash_flow",
  "financing_cash_flow",
  "accounts_receivable",
  "inventory",
  "accounts_payable",
  "cash_and_cash_equivalents",
  "cash_and_short_term_investments",
  "assets",
  "liabilities",
  "short_term_debt",
  "long_term_debt",
  "total_debt",
  "stockholders_equity",
  "common_stock_and_apic",
  "retained_earnings",
  "share_based_compensation",
  "shares_outstanding",
  "public_float",
  "energy_exploration_expense",
  "oil_gas_capitalized_costs",
  "energy_inventory",
  "energy_input_cost",
  "energy_revenue",
] as const;

export type SecMetricKey = (typeof SEC_METRIC_KEYS)[number];

const SEC_METRIC_KEY_SET = new Set<string>(SEC_METRIC_KEYS);

export function isSecMetricKey(value: string): value is SecMetricKey {
  return SEC_METRIC_KEY_SET.has(value);
}
