CREATE TABLE IF NOT EXISTS public.ticker_factor_signal_definitions (
  id BIGSERIAL PRIMARY KEY,

  model_key TEXT NOT NULL,
  model_version TEXT NOT NULL,

  factor TEXT NOT NULL,
  axis TEXT NOT NULL,

  signal_key TEXT NOT NULL,
  signal_label TEXT NOT NULL,
  signal_description TEXT,

  priority INTEGER NOT NULL DEFAULT 100,

  selection_rules JSONB NOT NULL,
  evidence_rules JSONB NOT NULL,
  confidence_rules JSONB NOT NULL,

  is_active BOOLEAN NOT NULL DEFAULT true,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_ticker_factor_signal_definitions UNIQUE (
    model_key,
    model_version,
    factor,
    axis,
    signal_key
  ),

  CONSTRAINT chk_tfsd_selection_rules_object
  CHECK (jsonb_typeof(selection_rules) = 'object'),

  CONSTRAINT chk_tfsd_evidence_rules_object
  CHECK (jsonb_typeof(evidence_rules) = 'object'),

  CONSTRAINT chk_tfsd_confidence_rules_object
  CHECK (jsonb_typeof(confidence_rules) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_tfsd_active_lookup
ON public.ticker_factor_signal_definitions (
  factor,
  axis,
  is_active,
  priority
);

CREATE INDEX IF NOT EXISTS idx_tfsd_model_lookup
ON public.ticker_factor_signal_definitions (
  model_key,
  model_version,
  factor,
  axis
);

DELETE FROM public.ticker_factor_signal_definitions
WHERE model_key = 'factor_signal'
  AND model_version = 'v0';

INSERT INTO public.ticker_factor_signal_definitions (
  model_key,
  model_version,
  factor,
  axis,
  signal_key,
  signal_label,
  signal_description,
  priority,
  selection_rules,
  evidence_rules,
  confidence_rules
)
VALUES
  (
    'factor_signal',
    'v0',
    'credit_sensitive',
    'market_price',
    'credit_stress_vulnerable',
    'Credit Stress Vulnerable',
    'The stock underperforms SPY on credit-spread widening days and sharper credit-spread shock days.',
    10,
    '{"all":[{"featureKey":"creditSpreadWideningRelativeReturn1Y","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":1},{"featureKey":"creditShockRelativeReturn1Y","aggregate":"latest_median","operator":"<=","value":-0.02,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["creditSpreadWideningRelativeReturn1Y","creditShockRelativeReturn1Y","creditSpreadWideningRelativeReturn3Y","highYieldSpreadBeta3Y","investmentGradeSpreadBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'credit_sensitive',
    'market_price',
    'credit_stress_resilient',
    'Credit Stress Resilient',
    'The stock holds up better than SPY during credit-spread widening days.',
    20,
    '{"all":[{"featureKey":"creditSpreadWideningRelativeReturn1Y","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"creditSpreadWideningRelativeReturn3Y","aggregate":"latest_median","operator":">=","value":0.02,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["creditSpreadWideningRelativeReturn1Y","creditSpreadWideningRelativeReturn3Y","creditShockRelativeReturn1Y","highYieldSpreadBeta3Y","investmentGradeSpreadBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'duration_sensitive',
    'market_price',
    'long_duration_sensitive',
    'Long-Duration Sensitive',
    'The stock behaves like a long-duration asset, moving with long Treasury prices and tending to weaken when long rates rise.',
    10,
    '{"all":[{"featureKey":"longBondBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1},{"featureKey":"ultraLongRateBeta3Y","aggregate":"latest_median","operator":"<=","value":-0.01,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["longBondBeta3Y","ultraLongRateBeta3Y","intermediateTreasuryBeta3Y","intermediateRateBeta3Y","yieldCurveBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'duration_sensitive',
    'market_price',
    'intermediate_duration_sensitive',
    'Intermediate-Duration Sensitive',
    'The stock has meaningful co-movement with intermediate-duration Treasury prices, but long-duration confirmation is weaker or mixed.',
    20,
    '{"all":[{"featureKey":"intermediateTreasuryBeta3Y","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["intermediateTreasuryBeta3Y","intermediateRateBeta3Y","longBondBeta3Y","ultraLongRateBeta3Y","yieldCurveBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'duration_sensitive',
    'market_price',
    'short_rate_sensitive',
    'Short-Rate Sensitive',
    'The stock has tended to weaken when front-end Treasury yields rise.',
    30,
    '{"all":[{"featureKey":"shortRateBeta3Y","aggregate":"latest_median","operator":"<=","value":-0.01,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["shortRateBeta3Y","shortTreasuryBeta3Y","intermediateRateBeta3Y","ultraLongRateBeta3Y","yieldCurveBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'duration_sensitive',
    'market_price',
    'duration_resilient',
    'Duration Resilient',
    'The stock has low long-bond co-movement and has not shown strong weakness when long rates rise.',
    40,
    '{"all":[{"featureKey":"longBondBeta3Y","aggregate":"latest_median","operator":"<=","value":0.2,"minObservedMetricCount":1},{"featureKey":"ultraLongRateBeta3Y","aggregate":"latest_median","operator":">=","value":-0.005,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["longBondBeta3Y","ultraLongRateBeta3Y","intermediateTreasuryBeta3Y","shortRateBeta3Y","yieldCurveBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'duration_sensitive',
    'market_price',
    'mixed_duration_sensitivity',
    'Mixed Duration Sensitivity',
    'Duration-sensitive market price features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["longBondBeta3Y","intermediateTreasuryBeta3Y","shortTreasuryBeta3Y","ultraLongRateBeta3Y","shortRateBeta3Y","yieldCurveBeta3Y"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'etf_exposure',
    'energy_etf_exposed',
    'Energy ETF Exposed',
    'The stock trades with broad energy sector ETF proxies.',
    10,
    '{"any":[{"featureKey":"energySectorBeta3Y","aggregate":"latest_median","operator":">=","value":0.8,"minObservedMetricCount":1},{"featureKey":"energyExplorationBeta3Y","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1},{"featureKey":"oilServicesBeta3Y","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["energySectorBeta3Y","energyExplorationBeta3Y","oilServicesBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'etf_exposure',
    'mixed_energy_etf_exposure',
    'Mixed Energy ETF Exposure',
    'Energy ETF exposure features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["energySectorBeta3Y","energyExplorationBeta3Y","oilServicesBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'commodity_linked',
    'etf_exposure',
    'commodity_etf_exposed',
    'Commodity ETF Exposed',
    'The stock trades with broad commodity or precious-metals ETF proxies.',
    10,
    '{"any":[{"featureKey":"broadCommodityBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1},{"featureKey":"goldBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1},{"featureKey":"silverBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["broadCommodityBeta3Y","goldBeta3Y","silverBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'commodity_linked',
    'etf_exposure',
    'mixed_commodity_etf_exposure',
    'Mixed Commodity ETF Exposure',
    'Commodity ETF exposure features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["broadCommodityBeta3Y","goldBeta3Y","silverBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'consumer_linked',
    'etf_exposure',
    'consumer_cyclical_etf_exposed',
    'Consumer Cyclical ETF Exposed',
    'The stock trades with consumer discretionary or retail ETF proxies.',
    10,
    '{"any":[{"featureKey":"consumerDiscretionaryBeta3Y","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1},{"featureKey":"retailBeta3Y","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["consumerDiscretionaryBeta3Y","retailBeta3Y","consumerStaplesBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'consumer_linked',
    'etf_exposure',
    'consumer_staples_etf_exposed',
    'Consumer Staples ETF Exposed',
    'The stock trades more like consumer staples than discretionary consumer proxies.',
    20,
    '{"all":[{"featureKey":"consumerStaplesBeta3Y","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1},{"featureKey":"consumerDiscretionaryBeta3Y","aggregate":"latest_median","operator":"<=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["consumerStaplesBeta3Y","consumerDiscretionaryBeta3Y","retailBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'consumer_linked',
    'etf_exposure',
    'mixed_consumer_etf_exposure',
    'Mixed Consumer ETF Exposure',
    'Consumer ETF exposure features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["consumerDiscretionaryBeta3Y","consumerStaplesBeta3Y","retailBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'inflation_hedge',
    'etf_exposure',
    'inflation_hedge_etf_exposed',
    'Inflation-Hedge ETF Exposed',
    'The stock trades with an inflation-hedge proxy basket of gold, broad commodities, and energy.',
    10,
    '{"all":[{"featureKey":"inflationHedgeBasketBeta3Y","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["inflationHedgeBasketBeta3Y"],"maxPresentedItems":1}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'inflation_hedge',
    'etf_exposure',
    'mixed_inflation_hedge_etf_exposure',
    'Mixed Inflation-Hedge ETF Exposure',
    'Inflation-hedge ETF exposure features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["inflationHedgeBasketBeta3Y"],"maxPresentedItems":1}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'reshoring_defense',
    'etf_exposure',
    'defense_etf_exposed',
    'Defense ETF Exposed',
    'The stock trades with aerospace and defense ETF proxies.',
    10,
    '{"all":[{"featureKey":"aerospaceDefenseBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["aerospaceDefenseBeta3Y","infrastructureBeta3Y","powerGridBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'reshoring_defense',
    'etf_exposure',
    'infrastructure_etf_exposed',
    'Infrastructure ETF Exposed',
    'The stock trades with U.S. infrastructure or power-grid ETF proxies.',
    20,
    '{"any":[{"featureKey":"infrastructureBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1},{"featureKey":"powerGridBeta3Y","aggregate":"latest_median","operator":">=","value":0.6,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["infrastructureBeta3Y","powerGridBeta3Y","aerospaceDefenseBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'reshoring_defense',
    'etf_exposure',
    'mixed_reshoring_defense_etf_exposure',
    'Mixed Reshoring & Defense ETF Exposure',
    'Reshoring and defense ETF exposure features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["aerospaceDefenseBeta3Y","infrastructureBeta3Y","powerGridBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'china_exposure',
    'etf_exposure',
    'china_etf_exposed',
    'China ETF Exposed',
    'The stock trades with China large-cap or China internet ETF proxies.',
    10,
    '{"any":[{"featureKey":"chinaLargeCapBeta3Y","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1},{"featureKey":"chinaInternetBeta3Y","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["chinaLargeCapBeta3Y","chinaInternetBeta3Y","emergingMarketBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'china_exposure',
    'etf_exposure',
    'emerging_market_etf_exposed',
    'Emerging Market ETF Exposed',
    'The stock trades with broad emerging market ETF proxies without strong China-specific confirmation.',
    20,
    '{"all":[{"featureKey":"emergingMarketBeta3Y","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["emergingMarketBeta3Y","chinaLargeCapBeta3Y","chinaInternetBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'china_exposure',
    'etf_exposure',
    'mixed_china_etf_exposure',
    'Mixed China ETF Exposure',
    'China and emerging-market ETF exposure features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["chinaLargeCapBeta3Y","chinaInternetBeta3Y","emergingMarketBeta3Y"],"maxPresentedItems":3}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'credit_sensitive',
    'market_price',
    'credit_shock_vulnerable',
    'Credit Shock Vulnerable',
    'The stock underperforms SPY on sharper high-yield spread widening days, even if broader credit sensitivity is mixed.',
    30,
    '{"all":[{"featureKey":"creditShockRelativeReturn1Y","aggregate":"latest_median","operator":"<=","value":-0.04,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["creditShockRelativeReturn1Y","creditSpreadWideningRelativeReturn1Y","creditSpreadWideningRelativeReturn3Y","highYieldSpreadBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'credit_sensitive',
    'market_price',
    'high_yield_spread_sensitive',
    'High-Yield Spread Sensitive',
    'The stock repeatedly underperforms SPY on high-yield credit-spread widening days.',
    40,
    '{"all":[{"featureKey":"creditSpreadWideningRelativeReturn3Y","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["creditSpreadWideningRelativeReturn3Y","creditSpreadWideningRelativeReturn1Y","creditShockRelativeReturn1Y","highYieldSpreadBeta3Y","investmentGradeSpreadBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'credit_sensitive',
    'market_price',
    'mixed_credit_sensitivity',
    'Mixed Credit Sensitivity',
    'Credit sensitivity features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["creditSpreadWideningRelativeReturn1Y","creditSpreadWideningRelativeReturn3Y","creditShockRelativeReturn1Y","highYieldSpreadBeta3Y","investmentGradeSpreadBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'fundamentals_based',
    'turnaround_growth',
    'Turnaround Growth',
    'Sign-sensitive growth metrics are moving out of loss or deterioration.',
    10,
    '{"all":[{"featureKey":"turnaroundMomentum","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["turnaroundMomentum"],"maxPresentedItems":4}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'fundamentals_based',
    'accelerating_growth',
    'Accelerating Growth',
    'Durable growth is positive and recent YoY momentum is improving.',
    20,
    '{"all":[{"featureKey":"durableGrowth","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":2},{"featureKey":"yoyGrowthAcceleration","aggregate":"latest_median","operator":">=","value":0.02,"minObservedMetricCount":2}]}'::jsonb,
    '{"supportingFeatureKeys":["durableGrowth","yoyGrowthAcceleration","latestGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'fundamentals_based',
    'durable_growth',
    'Durable Growth',
    'Trailing growth is positive across multiple growth metrics.',
    30,
    '{"all":[{"featureKey":"durableGrowth","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":2}]}'::jsonb,
    '{"supportingFeatureKeys":["durableGrowth","latestGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'fundamentals_based',
    'tentative_growth',
    'Tentative Growth',
    'Latest growth is positive, but durable confirmation is weaker or incomplete.',
    40,
    '{"all":[{"featureKey":"latestGrowth","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":2}]}'::jsonb,
    '{"supportingFeatureKeys":["latestGrowth"],"contextFeatureKeys":["durableGrowth","yoyGrowthAcceleration"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'fundamentals_based',
    'contracting_growth',
    'Contracting Growth',
    'Latest or trailing growth is negative across multiple growth metrics.',
    50,
    '{"any":[{"featureKey":"latestGrowth","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":2},{"featureKey":"durableGrowth","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":2}]}'::jsonb,
    '{"supportingFeatureKeys":["latestGrowth","durableGrowth","yoyGrowthAcceleration"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'fundamentals_based',
    'mixed_growth',
    'Mixed Growth',
    'Growth features are incomplete, flat, or mixed without a clear directional state.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["latestGrowth","durableGrowth","yoyGrowthAcceleration","turnaroundMomentum"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'quality',
    'fundamentals_based',
    'quality_concern',
    'Quality Concern',
    'Earnings quality or profitability quality shows cash conversion, accrual, or profitability pressure.',
    10,
    '{"any":[{"featureKey":"cashEarningsCoverage","aggregate":"latest_median","operator":"<","value":0.8,"minObservedMetricCount":1},{"featureKey":"accrualsToAssets","aggregate":"latest_median","operator":">","value":0.05,"minObservedMetricCount":1},{"featureKey":"profitabilityPosition","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":2},{"featureKey":"profitabilityTurnaround","aggregate":"latest_median","operator":"<=","value":-0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["cashEarningsCoverage","accrualsToAssets","profitabilityPosition","profitabilityTurnaround","profitabilityConsistency"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'quality',
    'fundamentals_based',
    'cash_backed_earnings',
    'Cash-Backed Earnings',
    'Reported earnings are supported by operating cash flow and low accrual pressure.',
    20,
    '{"all":[{"featureKey":"cashEarningsCoverage","aggregate":"latest_median","operator":">=","value":1,"minObservedMetricCount":1},{"featureKey":"accrualsToAssets","aggregate":"latest_median","operator":"<=","value":0.02,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["cashEarningsCoverage","accrualsToAssets","profitabilityConsistency","profitabilityPosition"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'quality',
    'fundamentals_based',
    'capital_efficient_quality',
    'Capital Efficient Quality',
    'Profitability is high relative to the asset base.',
    30,
    '{"any":[{"featureKey":"grossProfitToAssets","aggregate":"latest_median","operator":">=","value":0.1,"minObservedMetricCount":1},{"featureKey":"operatingReturnOnAssets","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"netIncomeReturnOnAssets","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["grossProfitToAssets","operatingReturnOnAssets","netIncomeReturnOnAssets","cashEarningsCoverage","accrualsToAssets"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'quality',
    'fundamentals_based',
    'consistent_profitability',
    'Consistent Profitability',
    'Profitability is consistently positive across observed profitability and cash-flow metrics.',
    40,
    '{"all":[{"featureKey":"profitabilityConsistency","aggregate":"latest_median","operator":">=","value":0.75,"minObservedMetricCount":2}]}'::jsonb,
    '{"supportingFeatureKeys":["profitabilityConsistency","profitabilityPosition","profitabilityTurnaround","cashEarningsCoverage"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'quality',
    'fundamentals_based',
    'improving_profitability',
    'Improving Profitability',
    'Profitability is above recent run-rate or turning around.',
    50,
    '{"any":[{"featureKey":"profitabilityPosition","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":2},{"featureKey":"profitabilityTurnaround","aggregate":"latest_median","operator":">=","value":0.5,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["profitabilityPosition","profitabilityTurnaround","profitabilityConsistency"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'quality',
    'fundamentals_based',
    'mixed_quality',
    'Mixed Quality',
    'Quality features are incomplete or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["profitabilityConsistency","profitabilityPosition","profitabilityTurnaround","cashEarningsCoverage","accrualsToAssets","grossProfitToAssets","operatingReturnOnAssets","netIncomeReturnOnAssets"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'fundamentals_based',
    'reliable_dividend_income',
    'Reliable Dividend Income',
    'Dividend consistency is high across observed dividend metrics.',
    10,
    '{"all":[{"featureKey":"dividendConsistency","aggregate":"latest_median","operator":">=","value":0.75,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["dividendConsistency","dividendPosition","dividendMomentum"],"contextFeatureKeys":["dividendCoverageRatio","dividendPayoutRatio"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'fundamentals_based',
    'growing_shareholder_return',
    'Growing Shareholder Return',
    'Dividend momentum or net share count reduction is improving.',
    20,
    '{"any":[{"featureKey":"dividendMomentum","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"shareCountReduction","aggregate":"latest_median","operator":">=","value":0.01,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["dividendMomentum","shareCountReduction","dividendPosition"],"contextFeatureKeys":["dividendCoverageRatio","dividendPayoutRatio"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'fundamentals_based',
    'unsupported_shareholder_return',
    'Unsupported Shareholder Return',
    'Dividend payout or shareholder return coverage appears weak.',
    30,
    '{"any":[{"featureKey":"dividendCoverageRatio","aggregate":"latest_median","operator":"<","value":1,"minObservedMetricCount":1},{"featureKey":"dividendPayoutRatio","aggregate":"latest_median","operator":">","value":0.9,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["dividendCoverageRatio","dividendPayoutRatio","dividendConsistency","dividendMomentum"],"contextFeatureKeys":["shareCountReduction"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'fundamentals_based',
    'mixed_shareholder_return',
    'Mixed Shareholder Return',
    'Shareholder return features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["dividendConsistency","dividendPosition","dividendMomentum","dividendCoverageRatio","dividendPayoutRatio","shareCountReduction"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'market_price',
    'defensive_market_behavior',
    'Defensive Market Behavior',
    'The stock tends to hold up better than SPY on down-market and volatility-stress days.',
    10,
    '{"all":[{"featureKey":"downMarketDefense1Y","aggregate":"latest_median","operator":">=","value":0.00,"minObservedMetricCount":1},{"featureKey":"downMarketDefense3Y","aggregate":"latest_median","operator":">=","value":0.00,"minObservedMetricCount":1},{"featureKey":"downsideCaptureDefense1Y","aggregate":"latest_median","operator":">=","value":0.15,"minObservedMetricCount":1}],"any":[{"featureKey":"volatilityStressDefense1Y","aggregate":"latest_median","operator":">=","value":0.00,"minObservedMetricCount":1},{"featureKey":"drawdownDefense1Y","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["downMarketDefense1Y","downMarketDefense3Y","downsideCaptureDefense1Y","volatilityStressDefense1Y","drawdownDefense1Y"],"contextFeatureKeys":["volatilityStressDefense3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'market_price',
    'volatility_stress_resilience',
    'Volatility Stress Resilience',
    'The stock holds up better than SPY when VIX is elevated, even if general down-market confirmation is less complete.',
    20,
    '{"all":[{"featureKey":"volatilityStressDefense1Y","aggregate":"latest_median","operator":">=","value":0.00,"minObservedMetricCount":1},{"featureKey":"volatilityStressDefense3Y","aggregate":"latest_median","operator":">=","value":0.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["volatilityStressDefense1Y","volatilityStressDefense3Y"],"contextFeatureKeys":["downMarketDefense1Y","downMarketDefense3Y","drawdownDefense1Y","downsideCaptureDefense1Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'market_price',
    'defensive_market_breakdown',
    'Defensive Market Breakdown',
    'The stock tends to perform worse than SPY during down-market, stress, or drawdown conditions.',
    30,
    '{"any":[{"featureKey":"downMarketDefense1Y","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":1},{"featureKey":"volatilityStressDefense1Y","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":1},{"featureKey":"downsideCaptureDefense1Y","aggregate":"latest_median","operator":"<=","value":-0.10,"minObservedMetricCount":1},{"featureKey":"drawdownDefense1Y","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["downMarketDefense1Y","volatilityStressDefense1Y","downsideCaptureDefense1Y","drawdownDefense1Y","downMarketDefense3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'market_price',
    'mixed_defensive_market_behavior',
    'Mixed Defensive Market Behavior',
    'Market-price defensive behavior features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["downMarketDefense1Y","downMarketDefense3Y","volatilityStressDefense1Y","volatilityStressDefense3Y","drawdownDefense1Y","downsideCaptureDefense1Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'fundamentals_based',
    'strong_defensive_profile',
    'Strong Defensive Profile',
    'Defensive stability or balance-sheet relief features are strong.',
    10,
    '{"any":[{"featureKey":"defensiveStability","aggregate":"latest_median","operator":">=","value":0.75,"minObservedMetricCount":2},{"featureKey":"defensiveBurdenRelief","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"defensiveBurdenContractionConsistency","aggregate":"latest_median","operator":">=","value":0.75,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["defensiveStability","defensiveBurdenRelief","defensiveBurdenContractionConsistency","defensiveBufferPosition"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'fundamentals_based',
    'defensive_pressure',
    'Defensive Pressure',
    'Defensive buffer or burden features are weakening.',
    20,
    '{"any":[{"featureKey":"defensiveBufferPosition","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":2},{"featureKey":"defensiveBurdenRelief","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":1},{"featureKey":"defensiveShockAbsorption","aggregate":"latest_median","operator":"<=","value":0.25,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["defensiveBufferPosition","defensiveBurdenRelief","defensiveShockAbsorption"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'defensive',
    'fundamentals_based',
    'mixed_defensive_profile',
    'Mixed Defensive Profile',
    'Defensive features are incomplete or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["defensiveStability","defensiveBufferPosition","defensiveShockAbsorption","defensiveBurdenRelief","defensiveBurdenTrendRelief","defensiveBurdenContractionConsistency"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'capex_cycle',
    'fundamentals_based',
    'capex_expansion',
    'CapEx Expansion',
    'CapEx investment intensity and annual investment level are rising with near-term confirmation.',
    10,
    '{"all":[{"featureKey":"capexInvestmentIntensityChange","aggregate":"latest_median","operator":">=","value":0.01,"minObservedMetricCount":2},{"featureKey":"capexCycleAnnualStretch","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":2}],"any":[{"featureKey":"capexCycleQuarterStretch","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"capexCycleAcceleration","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["capexInvestmentIntensityChange","capexCycleAnnualStretch","capexCycleQuarterStretch","capexCycleAcceleration"],"contextFeatureKeys":["capexTtmIncreaseValue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'capex_cycle',
    'fundamentals_based',
    'emerging_capex_cycle',
    'Emerging CapEx Cycle',
    'CapEx quarter intensity and acceleration are rising before a large annual expansion is established.',
    20,
    '{"all":[{"featureKey":"capexCycleQuarterStretch","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"capexCycleAcceleration","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"capexCycleAnnualStretch","aggregate":"latest_median","operator":"<","value":0.10,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["capexCycleQuarterStretch","capexCycleAcceleration","capexCycleAnnualStretch","capexInvestmentIntensityChange"],"contextFeatureKeys":["capexTtmIncreaseValue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'capex_cycle',
    'fundamentals_based',
    'capex_accelerating',
    'CapEx Accelerating',
    'CapEx cycle acceleration is positive across observed investment metrics.',
    30,
    '{"all":[{"featureKey":"capexCycleAcceleration","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["capexCycleAcceleration","capexCycleQuarterStretch","capexInvestmentIntensityChange","capexCycleAnnualStretch"],"contextFeatureKeys":["capexTtmIncreaseValue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'capex_cycle',
    'fundamentals_based',
    'capex_pullback',
    'CapEx Pullback',
    'CapEx investment intensity or annual investment level is declining.',
    40,
    '{"any":[{"featureKey":"capexInvestmentIntensityChange","aggregate":"latest_median","operator":"<=","value":-0.01,"minObservedMetricCount":2},{"featureKey":"capexCycleAnnualStretch","aggregate":"latest_median","operator":"<=","value":-0.10,"minObservedMetricCount":2}]}'::jsonb,
    '{"supportingFeatureKeys":["capexInvestmentIntensityChange","capexCycleAnnualStretch","capexCycleAcceleration","capexCycleQuarterStretch"],"contextFeatureKeys":["capexTtmIncreaseValue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":2,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'capex_cycle',
    'fundamentals_based',
    'mixed_capex_cycle',
    'Mixed CapEx Cycle',
    'CapEx cycle features are incomplete, flat, or mixed without a clear directional state.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["capexInvestmentIntensityChange","capexCycleAcceleration","capexCycleQuarterStretch","capexCycleAnnualStretch"],"contextFeatureKeys":["capexTtmIncreaseValue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'fundamentals_based',
    'energy_activity_ramping',
    'Energy Activity Ramping',
    'Energy-linked revenue or exploration activity metrics are increasing across observed metrics.',
    10,
    '{"all":[{"featureKey":"energyActivityGrowth","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["energyActivityGrowth","energyActivityAcceleration","energyActivityStretch"],"contextFeatureKeys":["energyCostPressure","energyAssetInventoryGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'fundamentals_based',
    'energy_asset_or_inventory_build',
    'Energy Asset or Inventory Build',
    'Energy-linked asset base or commodity inventory is elevated versus recent history.',
    20,
    '{"any":[{"featureKey":"energyAssetInventoryStretch","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"energyAssetInventoryGrowth","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["energyAssetInventoryStretch","energyAssetInventoryGrowth","energyAssetInventoryAcceleration"],"contextFeatureKeys":["energyActivityGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'fundamentals_based',
    'energy_cost_pressure',
    'Energy Cost Pressure',
    'Energy input costs are rising, indicating margin pressure or pass-through risk.',
    30,
    '{"all":[{"featureKey":"energyCostPressure","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["energyCostPressure","energyCostAcceleration","energyCostStretch"],"contextFeatureKeys":["energyActivityGrowth","energyAssetInventoryGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'fundamentals_based',
    'energy_activity_fading',
    'Energy Activity Fading',
    'Energy-linked revenue or exploration activity metrics are declining across observed metrics.',
    40,
    '{"all":[{"featureKey":"energyActivityGrowth","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["energyActivityGrowth","energyActivityAcceleration","energyActivityStretch"],"contextFeatureKeys":["energyAssetInventoryGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":2}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'energy_linked',
    'fundamentals_based',
    'mixed_energy_exposure',
    'Mixed Energy Exposure',
    'Energy-linked features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["energyActivityGrowth","energyActivityAcceleration","energyActivityStretch","energyAssetInventoryGrowth","energyAssetInventoryAcceleration","energyAssetInventoryStretch","energyCostPressure","energyCostAcceleration","energyCostStretch"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'liquidity_sensitive',
    'fundamentals_based',
    'working_capital_build',
    'Working Capital Build',
    'Receivables or inventory are elevated versus recent history, indicating working capital is being tied up.',
    10,
    '{"any":[{"featureKey":"receivablesBuild","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"inventoryBuild","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["receivablesBuild","inventoryBuild","receivablesToRevenue","inventoryToRevenue"],"contextFeatureKeys":["receivablesChange","inventoryChange","payablesBuild"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'liquidity_sensitive',
    'fundamentals_based',
    'receivables_collection_pressure',
    'Receivables Collection Pressure',
    'Receivables are increasing, building versus recent history, and high relative to revenue.',
    20,
    '{"any":[{"featureKey":"receivablesToRevenue","aggregate":"latest_median","operator":">=","value":0.20,"minObservedMetricCount":1}],"all":[{"featureKey":"receivablesChange","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"receivablesBuild","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["receivablesToRevenue","receivablesChange","receivablesBuild"],"contextFeatureKeys":["payablesChange","payablesToRevenue","inventoryChange"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'liquidity_sensitive',
    'fundamentals_based',
    'inventory_overhang_pressure',
    'Inventory Overhang Pressure',
    'Inventory is increasing, building versus recent history, and high relative to revenue.',
    25,
    '{"any":[{"featureKey":"inventoryToRevenue","aggregate":"latest_median","operator":">=","value":0.20,"minObservedMetricCount":1}],"all":[{"featureKey":"inventoryChange","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"inventoryBuild","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["inventoryToRevenue","inventoryChange","inventoryBuild"],"contextFeatureKeys":["receivablesChange","payablesChange","payablesToRevenue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'liquidity_sensitive',
    'fundamentals_based',
    'payables_financing_reliance',
    'Payables Financing Reliance',
    'Payables are elevated or increasing, suggesting cash preservation through supplier financing or delayed payments.',
    30,
    '{"any":[{"featureKey":"payablesToRevenue","aggregate":"latest_median","operator":">=","value":0.15,"minObservedMetricCount":1}],"all":[{"featureKey":"payablesChange","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"payablesBuild","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["payablesChange","payablesBuild","payablesToRevenue"],"contextFeatureKeys":["receivablesChange","inventoryChange"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'liquidity_sensitive',
    'fundamentals_based',
    'working_capital_release',
    'Working Capital Release',
    'Receivables or inventory are below recent run-rate, indicating working capital is being released.',
    40,
    '{"any":[{"featureKey":"receivablesBuild","aggregate":"latest_median","operator":"<=","value":-0.10,"minObservedMetricCount":1},{"featureKey":"inventoryBuild","aggregate":"latest_median","operator":"<=","value":-0.10,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["receivablesBuild","inventoryBuild","receivablesChange","inventoryChange"],"contextFeatureKeys":["payablesBuild"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'liquidity_sensitive',
    'fundamentals_based',
    'mixed_liquidity_sensitivity',
    'Mixed Liquidity Sensitivity',
    'Working-capital liquidity features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["receivablesChange","receivablesBuild","receivablesToRevenue","inventoryChange","inventoryBuild","inventoryToRevenue","payablesChange","payablesBuild","payablesToRevenue"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'fundamentals_based',
    'book_value_support',
    'Book Value Support',
    'Book equity provides a meaningful balance-sheet value anchor relative to total assets.',
    10,
    '{"all":[{"featureKey":"bookEquityToAssets","aggregate":"latest_median","operator":">=","value":0.35,"minObservedMetricCount":1}],"any":[{"featureKey":"liabilitiesToAssets","aggregate":"latest_median","operator":"<=","value":0.65,"minObservedMetricCount":1},{"featureKey":"debtToAssets","aggregate":"latest_median","operator":"<=","value":0.30,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["bookEquityToAssets","liabilitiesToAssets","debtToAssets","retainedEarningsToAssets"],"contextFeatureKeys":["assetBaseGrowth","bookEquityGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'fundamentals_based',
    'liquid_asset_support',
    'Liquid Asset Support',
    'Cash and book equity provide a liquid balance-sheet value cushion.',
    20,
    '{"all":[{"featureKey":"cashToAssets","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"bookEquityToAssets","aggregate":"latest_median","operator":">=","value":0.20,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["cashToAssets","bookEquityToAssets","liabilitiesToAssets","debtToAssets"],"contextFeatureKeys":["assetBasePosition","bookEquityPosition"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'fundamentals_based',
    'book_value_building',
    'Book Value Building',
    'Book equity or accumulated retained earnings are building relative to the asset base.',
    30,
    '{"any":[{"featureKey":"bookEquityGrowth","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"bookEquityPosition","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"retainedEarningsToAssets","aggregate":"latest_median","operator":">=","value":0.15,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["bookEquityGrowth","bookEquityPosition","retainedEarningsToAssets","bookEquityToAssets"],"contextFeatureKeys":["assetBaseGrowth","assetBasePosition"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'fundamentals_based',
    'levered_book_value_pressure',
    'Levered Book Value Pressure',
    'Book-value support is weak or balance-sheet leverage is high relative to assets.',
    40,
    '{"any":[{"featureKey":"bookEquityToAssets","aggregate":"latest_median","operator":"<=","value":0.10,"minObservedMetricCount":1},{"featureKey":"liabilitiesToAssets","aggregate":"latest_median","operator":">=","value":0.85,"minObservedMetricCount":1},{"featureKey":"debtToAssets","aggregate":"latest_median","operator":">=","value":0.50,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["bookEquityToAssets","liabilitiesToAssets","debtToAssets","cashToAssets"],"contextFeatureKeys":["bookEquityGrowth","assetBaseGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'fundamentals_based',
    'mixed_fundamental_value',
    'Mixed Fundamental Value',
    'Fundamental value-anchor features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["bookEquityToAssets","bookEquityGrowth","bookEquityPosition","retainedEarningsToAssets","cashToAssets","liabilitiesToAssets","debtToAssets","assetBaseGrowth","assetBasePosition"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'momentum',
    'market_price',
    'strong_price_momentum',
    'Strong Price Momentum',
    'Price trend is positive and outperforming SPY across the core momentum window.',
    10,
    '{"all":[{"featureKey":"priceMomentum12MEx1M","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"relativeMomentum12MEx1M","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"momentumConsistency12M","aggregate":"latest_median","operator":">=","value":0.58,"minObservedMetricCount":1},{"featureKey":"distanceFrom52WeekHigh","aggregate":"latest_median","operator":">=","value":-0.10,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceMomentum12MEx1M","relativeMomentum12MEx1M","momentumConsistency12M","distanceFrom52WeekHigh","priceReturn6M"],"contextFeatureKeys":["relativeReturn3M","relativeReturn6M","relativeReturn12M"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'momentum',
    'market_price',
    'market_leading_momentum',
    'Market-Leading Momentum',
    'Recent and trailing returns are stronger than SPY even if absolute confirmation is less complete.',
    20,
    '{"all":[{"featureKey":"relativeReturn6M","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"relativeReturn12M","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["relativeReturn6M","relativeReturn12M","relativeMomentum12MEx1M"],"contextFeatureKeys":["priceReturn6M","priceReturn12M","priceMomentum12MEx1M"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'momentum',
    'market_price',
    'absolute_price_momentum',
    'Absolute Price Momentum',
    'Absolute price momentum is positive, even if SPY-relative strength is weaker or incomplete.',
    30,
    '{"all":[{"featureKey":"priceMomentum12MEx1M","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceMomentum12MEx1M","priceReturn6M","priceReturn12M","momentumConsistency12M"],"contextFeatureKeys":["relativeMomentum12MEx1M","relativeReturn6M","relativeReturn12M"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'momentum',
    'market_price',
    'price_momentum_fading',
    'Price Momentum Fading',
    'Recent price action is weak, underperforming SPY, or the stock has fallen materially from its 52-week high.',
    40,
    '{"any":[{"featureKey":"priceReturn3M","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":1},{"featureKey":"relativeReturn6M","aggregate":"latest_median","operator":"<=","value":-0.05,"minObservedMetricCount":1},{"featureKey":"distanceFrom52WeekHigh","aggregate":"latest_median","operator":"<=","value":-0.20,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceReturn3M","relativeReturn6M","distanceFrom52WeekHigh","priceReturn6M","priceMomentum12MEx1M"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'momentum',
    'market_price',
    'mixed_price_momentum',
    'Mixed Price Momentum',
    'Price momentum features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["priceReturn3M","priceReturn6M","priceReturn12M","priceMomentum12MEx1M","relativeReturn3M","relativeReturn6M","relativeReturn12M","relativeMomentum12MEx1M","momentumConsistency12M","distanceFrom52WeekHigh"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'low_volatility',
    'market_price',
    'low_realized_volatility',
    'Low Realized Volatility',
    'Realized volatility is contained across recent and multi-year price windows, with drawdown retained as supporting risk context.',
    10,
    '{"all":[{"featureKey":"realizedVolatility1Y","aggregate":"latest_median","operator":"<=","value":0.20,"minObservedMetricCount":1},{"featureKey":"realizedVolatility3Y","aggregate":"latest_median","operator":"<=","value":0.22,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["realizedVolatility1Y","realizedVolatility3Y","downsideVolatility1Y","maxDrawdown1Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'low_volatility',
    'market_price',
    'elevated_volatility',
    'Elevated Volatility',
    'Realized volatility, downside volatility, or recent drawdown is elevated, weakening the low-volatility profile.',
    20,
    '{"any":[{"featureKey":"realizedVolatility1Y","aggregate":"latest_median","operator":">=","value":0.35,"minObservedMetricCount":1},{"featureKey":"downsideVolatility1Y","aggregate":"latest_median","operator":">=","value":0.20,"minObservedMetricCount":1},{"featureKey":"maxDrawdown1Y","aggregate":"latest_median","operator":"<=","value":-0.30,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["realizedVolatility1Y","maxDrawdown1Y","downsideVolatility1Y","realizedVolatility3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'low_volatility',
    'market_price',
    'mixed_volatility_profile',
    'Mixed Volatility Profile',
    'Volatility and drawdown features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["realizedVolatility1Y","realizedVolatility3Y","downsideVolatility1Y","maxDrawdown1Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'high_beta',
    'market_price',
    'elevated_market_beta',
    'Elevated Market Beta',
    'The stock has elevated regression beta versus SPY, with QQQ and DIA beta retained as context.',
    10,
    '{"all":[{"featureKey":"marketBeta1Y","aggregate":"latest_median","operator":">=","value":1.20,"minObservedMetricCount":1},{"featureKey":"marketBeta3Y","aggregate":"latest_median","operator":">=","value":1.10,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["marketBeta1Y","marketBeta3Y","correlationToMarket3Y","upsideCapture1Y","downsideCapture1Y"],"contextFeatureKeys":["qqqBeta1Y","qqqBeta3Y","qqqCorrelation3Y","diaBeta1Y","diaBeta3Y","diaCorrelation3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'high_beta',
    'market_price',
    'upside_capture',
    'Upside Capture',
    'The stock tends to capture more than the market on positive SPY-return days.',
    20,
    '{"all":[{"featureKey":"upsideCapture1Y","aggregate":"latest_median","operator":">=","value":1.10,"minObservedMetricCount":1},{"featureKey":"marketBeta1Y","aggregate":"latest_median","operator":">=","value":1.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["upsideCapture1Y","marketBeta1Y","marketBeta3Y","correlationToMarket3Y"],"contextFeatureKeys":["qqqBeta1Y","qqqBeta3Y","diaBeta1Y","diaBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'high_beta',
    'market_price',
    'downside_sensitivity',
    'Downside Sensitivity',
    'The stock tends to capture more than the market downside on negative SPY-return days.',
    30,
    '{"all":[{"featureKey":"downsideCapture1Y","aggregate":"latest_median","operator":">=","value":1.10,"minObservedMetricCount":1},{"featureKey":"marketBeta1Y","aggregate":"latest_median","operator":">=","value":1.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["downsideCapture1Y","marketBeta1Y","marketBeta3Y","correlationToMarket3Y"],"contextFeatureKeys":["qqqBeta1Y","qqqBeta3Y","diaBeta1Y","diaBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'high_beta',
    'market_price',
    'mixed_market_sensitivity',
    'Mixed Market Sensitivity',
    'Market sensitivity features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["marketBeta1Y","marketBeta3Y","correlationToMarket3Y","upsideCapture1Y","downsideCapture1Y"],"contextFeatureKeys":["qqqBeta1Y","qqqBeta3Y","qqqCorrelation3Y","diaBeta1Y","diaBeta3Y","diaCorrelation3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'valuation',
    'deep_value',
    'Deep Value',
    'Market valuation is very low against earnings, operating cash flow, or book value anchors.',
    10,
    '{"any":[{"featureKey":"priceToEarnings","aggregate":"latest_median","operator":"<=","value":12.00,"minObservedMetricCount":1},{"featureKey":"priceToOperatingCashFlow","aggregate":"latest_median","operator":"<=","value":10.00,"minObservedMetricCount":1},{"featureKey":"priceToBook","aggregate":"latest_median","operator":"<=","value":1.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToBook","priceToSales","priceToEarnings","priceToOperatingCashFlow","freeCashFlowYield","enterpriseValueToSales"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":6}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'valuation',
    'earnings_value',
    'Earnings Value',
    'Market valuation is reasonable or low relative to trailing earnings.',
    20,
    '{"all":[{"featureKey":"priceToEarnings","aggregate":"latest_median","operator":"<=","value":20.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToEarnings"],"contextFeatureKeys":["priceToOperatingCashFlow","freeCashFlowYield","priceToBook","priceToSales","enterpriseValueToSales"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":6}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'valuation',
    'cash_flow_value',
    'Cash Flow Value',
    'Market valuation is reasonable or low relative to trailing operating cash flow.',
    30,
    '{"all":[{"featureKey":"priceToOperatingCashFlow","aggregate":"latest_median","operator":"<=","value":15.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToOperatingCashFlow","freeCashFlowYield"],"contextFeatureKeys":["priceToEarnings","priceToBook","priceToSales","enterpriseValueToSales"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":6}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'valuation',
    'asset_value',
    'Asset Value',
    'Market valuation is reasonable or low relative to book equity.',
    40,
    '{"all":[{"featureKey":"priceToBook","aggregate":"latest_median","operator":"<=","value":3.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToBook"],"contextFeatureKeys":["priceToEarnings","priceToOperatingCashFlow","freeCashFlowYield","priceToSales","enterpriseValueToSales"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":6}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'valuation',
    'expensive_value',
    'Expensive Value',
    'Market valuation multiples are elevated against available fundamental anchors.',
    50,
    '{"any":[{"featureKey":"priceToBook","aggregate":"latest_median","operator":">=","value":8.00,"minObservedMetricCount":1},{"featureKey":"priceToSales","aggregate":"latest_median","operator":">=","value":8.00,"minObservedMetricCount":1},{"featureKey":"priceToEarnings","aggregate":"latest_median","operator":">=","value":35.00,"minObservedMetricCount":1},{"featureKey":"priceToOperatingCashFlow","aggregate":"latest_median","operator":">=","value":30.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToBook","priceToSales","enterpriseValueToSales","priceToEarnings","priceToOperatingCashFlow"],"contextFeatureKeys":["freeCashFlowYield"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":6}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'value',
    'valuation',
    'mixed_value_valuation',
    'Mixed Value Valuation',
    'Valuation features are incomplete, unavailable, or mixed across value anchors.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["priceToBook","priceToSales","enterpriseValueToSales","priceToEarnings","priceToOperatingCashFlow","freeCashFlowYield"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":6}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'valuation',
    'growth_premium',
    'Growth Premium',
    'The market is assigning a high earnings multiple while EPS growth is also strong.',
    10,
    '{"all":[{"featureKey":"priceToDilutedTtmEps","aggregate":"latest_median","operator":">=","value":30.00,"minObservedMetricCount":1},{"featureKey":"dilutedTtmEpsGrowth","aggregate":"latest_median","operator":">=","value":0.15,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToDilutedTtmEps","dilutedTtmEpsGrowth","priceToBasicTtmEps","basicTtmEpsGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'valuation',
    'reasonable_growth_valuation',
    'Reasonable Growth Valuation',
    'EPS growth is positive while the earnings multiple remains moderate.',
    20,
    '{"all":[{"featureKey":"dilutedTtmEpsGrowth","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1},{"featureKey":"priceToDilutedTtmEps","aggregate":"latest_median","operator":"<=","value":20.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["dilutedTtmEpsGrowth","priceToDilutedTtmEps","basicTtmEpsGrowth","priceToBasicTtmEps"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'valuation',
    'expensive_growth',
    'Expensive Growth',
    'The earnings multiple is high while EPS growth support is weak or modest.',
    30,
    '{"all":[{"featureKey":"priceToDilutedTtmEps","aggregate":"latest_median","operator":">=","value":40.00,"minObservedMetricCount":1},{"featureKey":"dilutedTtmEpsGrowth","aggregate":"latest_median","operator":"<","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["priceToDilutedTtmEps","dilutedTtmEpsGrowth","priceToBasicTtmEps","basicTtmEpsGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'growth',
    'valuation',
    'mixed_growth_valuation',
    'Mixed Growth Valuation',
    'Growth valuation features are incomplete, unavailable, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["priceToDilutedTtmEps","priceToBasicTtmEps","dilutedTtmEpsGrowth","basicTtmEpsGrowth"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":4}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'high_shareholder_yield',
    'High Shareholder Yield',
    'Total dividend plus repurchase yield is high relative to market capitalization.',
    10,
    '{"all":[{"featureKey":"shareholderYield","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["shareholderYield","dividendYield","buybackYield"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'high_dividend_yield',
    'High Dividend Yield',
    'Dividend yield is high relative to market capitalization.',
    20,
    '{"all":[{"featureKey":"dividendYield","aggregate":"latest_median","operator":">=","value":0.04,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["dividendYield","shareholderYield","dividendYieldShare","buybackYield"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'high_buyback_yield',
    'High Buyback Yield',
    'Repurchase yield is high relative to market capitalization.',
    30,
    '{"all":[{"featureKey":"buybackYield","aggregate":"latest_median","operator":">=","value":0.04,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["buybackYield","shareholderYield","buybackYieldShare","dividendYield"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'dividend_led_yield',
    'Dividend-Led Yield',
    'Income valuation is primarily supported by dividend yield.',
    40,
    '{"all":[{"featureKey":"shareholderYield","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"dividendYieldShare","aggregate":"latest_median","operator":">=","value":0.60,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["dividendYield","shareholderYield","dividendYieldShare","buybackYield","buybackYieldShare"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'buyback_led_yield',
    'Buyback-Led Yield',
    'Income valuation is primarily supported by repurchase yield.',
    50,
    '{"all":[{"featureKey":"shareholderYield","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"buybackYieldShare","aggregate":"latest_median","operator":">=","value":0.60,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["buybackYield","shareholderYield","buybackYieldShare","dividendYield","dividendYieldShare"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'low_shareholder_yield',
    'Low Shareholder Yield',
    'Dividend and repurchase yields are low relative to market capitalization.',
    60,
    '{"all":[{"featureKey":"shareholderYield","aggregate":"latest_median","operator":"<","value":0.02,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["shareholderYield","dividendYield","buybackYield","dividendYieldShare","buybackYieldShare"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'income',
    'valuation',
    'mixed_income_valuation',
    'Mixed Income Valuation',
    'Income valuation features are incomplete, unavailable, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["shareholderYield","dividendYield","buybackYield","dividendYieldShare","buybackYieldShare"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'fundamentals_based',
    'net_rate_cost_exposed',
    'Net Rate Cost Exposed',
    'Interest expense is meaningful relative to operating capacity, rising, and supported by debt exposure.',
    10,
    '{"all":[{"featureKey":"rateGrossInterestToOperatingCashFlow","aggregate":"latest_median","operator":">=","value":0.08,"minObservedMetricCount":1},{"featureKey":"rateInterestExpenseGrowth","aggregate":"latest_median","operator":">=","value":0.10,"minObservedMetricCount":1}],"any":[{"featureKey":"rateTotalDebtToAssets","aggregate":"latest_median","operator":">=","value":0.30,"minObservedMetricCount":1},{"featureKey":"rateShortTermDebtToAssets","aggregate":"latest_median","operator":">=","value":0.05,"minObservedMetricCount":1},{"featureKey":"rateShortTermDebtShare","aggregate":"latest_median","operator":">=","value":0.20,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateGrossInterestToOperatingCashFlow","rateGrossInterestToOperatingIncome","rateInterestExpenseGrowth","rateTotalDebtToAssets","rateShortTermDebtToAssets","rateShortTermDebtShare"],"contextFeatureKeys":["rateCashInvestmentsToInterestExpense","rateInterestIncomeToInterestExpense","rateNetInterestToOperatingCashFlow"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'fundamentals_based',
    'cash_offset_rate_exposure',
    'Cash-Offset Rate Exposure',
    'Interest-cost exposure exists, but cash, short-term investments, or interest income provide a meaningful offset.',
    20,
    '{"all":[{"featureKey":"rateGrossInterestToOperatingCashFlow","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1}],"any":[{"featureKey":"rateCashInvestmentsToInterestExpense","aggregate":"latest_median","operator":">=","value":3.00,"minObservedMetricCount":1},{"featureKey":"rateCashInvestmentsToTotalDebt","aggregate":"latest_median","operator":">=","value":0.50,"minObservedMetricCount":1},{"featureKey":"rateInterestIncomeToInterestExpense","aggregate":"latest_median","operator":">=","value":0.50,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateGrossInterestToOperatingCashFlow","rateCashInvestmentsToInterestExpense","rateCashInvestmentsToTotalDebt","rateCashToTotalDebt","rateInterestIncomeToInterestExpense","rateInterestIncomeToOperatingCashFlow"],"contextFeatureKeys":["rateTotalDebtToAssets","rateShortTermDebtShare","rateNetInterestToOperatingCashFlow"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'fundamentals_based',
    'net_rate_beneficiary',
    'Net Rate Beneficiary',
    'Interest income or liquid asset yield appears large enough to benefit from higher-rate conditions.',
    30,
    '{"any":[{"featureKey":"rateInterestIncomeToInterestExpense","aggregate":"latest_median","operator":">=","value":1.00,"minObservedMetricCount":1},{"featureKey":"rateInterestIncomeToOperatingCashFlow","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"rateCashInvestmentsToInterestExpense","aggregate":"latest_median","operator":">=","value":8.00,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateInterestIncomeToInterestExpense","rateInterestIncomeToOperatingCashFlow","rateInterestIncomeGrowth","rateCashInvestmentsToInterestExpense","rateCashInvestmentsToTotalDebt"],"contextFeatureKeys":["rateGrossInterestToOperatingCashFlow","rateNetInterestToOperatingCashFlow"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'fundamentals_based',
    'levered_but_liquid',
    'Levered but Liquid',
    'Debt exposure is visible, but liquid balances are large relative to debt.',
    40,
    '{"all":[{"featureKey":"rateTotalDebtToAssets","aggregate":"latest_median","operator":">=","value":0.30,"minObservedMetricCount":1},{"featureKey":"rateCashInvestmentsToTotalDebt","aggregate":"latest_median","operator":">=","value":0.50,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateTotalDebtToAssets","rateShortTermDebtToAssets","rateCashInvestmentsToTotalDebt","rateCashToTotalDebt","rateCashInvestmentsToInterestExpense"],"contextFeatureKeys":["rateGrossInterestToOperatingCashFlow","rateInterestExpenseGrowth"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'fundamentals_based',
    'low_rate_transmission',
    'Low Rate Transmission',
    'Interest expense and debt exposure are low, so higher rates appear less likely to transmit materially into reported fundamentals.',
    50,
    '{"all":[{"featureKey":"rateGrossInterestToOperatingCashFlow","aggregate":"latest_median","operator":"<=","value":0.03,"minObservedMetricCount":1},{"featureKey":"rateTotalDebtToAssets","aggregate":"latest_median","operator":"<=","value":0.20,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateGrossInterestToOperatingCashFlow","rateGrossInterestToOperatingIncome","rateTotalDebtToAssets","rateShortTermDebtToAssets","rateCashInvestmentsToInterestExpense","rateInterestIncomeToInterestExpense"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'fundamentals_based',
    'mixed_rate_fundamentals',
    'Mixed Rate Fundamentals',
    'Fundamental rate-sensitivity features are incomplete, unavailable, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["rateGrossInterestToOperatingCashFlow","rateGrossInterestToOperatingIncome","rateInterestExpenseGrowth","rateTotalDebtToAssets","rateShortTermDebtShare","rateCashInvestmentsToInterestExpense","rateInterestIncomeToInterestExpense","rateNetInterestToOperatingCashFlow"],"maxPresentedItems":6}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":3}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'market_price',
    'rate_pressure',
    'Rate Pressure',
    'The stock underperforms SPY on rising-rate days and sharper rate-up shock days.',
    10,
    '{"all":[{"featureKey":"rateUpRelativeReturn1Y","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":1},{"featureKey":"rateShockRelativeReturn1Y","aggregate":"latest_median","operator":"<=","value":-0.02,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateUpRelativeReturn1Y","rateShockRelativeReturn1Y","rateUpRelativeReturn3Y","rateBeta3Y","curveFlatteningRelativeReturn3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'market_price',
    'rate_resilient',
    'Rate Resilient',
    'The stock holds up better than SPY during rising-rate days.',
    20,
    '{"all":[{"featureKey":"rateUpRelativeReturn1Y","aggregate":"latest_median","operator":">=","value":0.03,"minObservedMetricCount":1},{"featureKey":"rateUpRelativeReturn3Y","aggregate":"latest_median","operator":">=","value":0.02,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateUpRelativeReturn1Y","rateUpRelativeReturn3Y","rateShockRelativeReturn1Y","rateBeta3Y","curveFlatteningRelativeReturn3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'market_price',
    'rate_shock_vulnerable',
    'Rate Shock Vulnerable',
    'The stock underperforms SPY on sharper 10-year Treasury yield jump days, even if broader rate sensitivity is mixed.',
    30,
    '{"all":[{"featureKey":"rateShockRelativeReturn1Y","aggregate":"latest_median","operator":"<=","value":-0.04,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["rateShockRelativeReturn1Y","rateUpRelativeReturn1Y","rateUpRelativeReturn3Y","rateBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'market_price',
    'curve_flattening_pressure',
    'Curve-Flattening Pressure',
    'The stock underperforms SPY on yield-curve flattening days.',
    40,
    '{"all":[{"featureKey":"curveFlatteningRelativeReturn3Y","aggregate":"latest_median","operator":"<=","value":-0.03,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["curveFlatteningRelativeReturn3Y","rateUpRelativeReturn3Y","rateBeta3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'rate_sensitive',
    'market_price',
    'mixed_rate_sensitivity',
    'Mixed Rate Sensitivity',
    'Rate sensitivity features are incomplete, flat, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["rateUpRelativeReturn1Y","rateUpRelativeReturn3Y","rateShockRelativeReturn1Y","rateBeta3Y","curveFlatteningRelativeReturn3Y"],"maxPresentedItems":5}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'cyclical',
    'macro_linked',
    'investment_cycle_cyclical',
    'Investment-Cycle Cyclical',
    'Revenue is sensitive to the U.S. private investment cycle and is confirmed by profit-cycle or investment-profit sensitivity.',
    10,
    '{"all":[{"featureKey":"investmentRevenueSensitivity","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1}],"any":[{"featureKey":"investmentProfitSensitivity","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1},{"featureKey":"corporateProfitSensitivity","aggregate":"latest_median","operator":">=","value":0.7,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["investmentRevenueSensitivity","investmentProfitSensitivity","corporateProfitSensitivity","gdpRevenueSensitivity"],"maxPresentedItems":4}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'cyclical',
    'macro_linked',
    'profit_cycle_cyclical',
    'Profit-Cycle Cyclical',
    'Operating income is sensitive to the broad U.S. corporate profit cycle with some investment-cycle confirmation.',
    20,
    '{"all":[{"featureKey":"corporateProfitSensitivity","aggregate":"latest_median","operator":">=","value":0.8,"minObservedMetricCount":1}],"any":[{"featureKey":"investmentRevenueSensitivity","aggregate":"latest_median","operator":">=","value":0.3,"minObservedMetricCount":1},{"featureKey":"investmentProfitSensitivity","aggregate":"latest_median","operator":">=","value":0.3,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["corporateProfitSensitivity","investmentRevenueSensitivity","investmentProfitSensitivity","gdpRevenueSensitivity"],"maxPresentedItems":4}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'cyclical',
    'macro_linked',
    'broad_macro_cyclical',
    'Broad Macro Cyclical',
    'Revenue is sensitive to broad GDP growth and has some investment or profit-cycle confirmation.',
    30,
    '{"all":[{"featureKey":"gdpRevenueSensitivity","aggregate":"latest_median","operator":">=","value":0.8,"minObservedMetricCount":1}],"any":[{"featureKey":"investmentRevenueSensitivity","aggregate":"latest_median","operator":">=","value":0.3,"minObservedMetricCount":1},{"featureKey":"corporateProfitSensitivity","aggregate":"latest_median","operator":">=","value":0.3,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["gdpRevenueSensitivity","investmentRevenueSensitivity","corporateProfitSensitivity","investmentProfitSensitivity"],"maxPresentedItems":4}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'cyclical',
    'macro_linked',
    'counter_cyclical_macro_defensive',
    'Counter-Cyclical / Macro Defensive',
    'Revenue and investment or profit sensitivity are negative, suggesting the company does not move with the macro expansion cycle.',
    40,
    '{"all":[{"featureKey":"gdpRevenueSensitivity","aggregate":"latest_median","operator":"<=","value":-0.3,"minObservedMetricCount":1}],"any":[{"featureKey":"investmentRevenueSensitivity","aggregate":"latest_median","operator":"<=","value":-0.3,"minObservedMetricCount":1},{"featureKey":"corporateProfitSensitivity","aggregate":"latest_median","operator":"<=","value":-0.3,"minObservedMetricCount":1}]}'::jsonb,
    '{"supportingFeatureKeys":["gdpRevenueSensitivity","investmentRevenueSensitivity","corporateProfitSensitivity","investmentProfitSensitivity"],"maxPresentedItems":4}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  ),
  (
    'factor_signal',
    'v0',
    'cyclical',
    'macro_linked',
    'mixed_macro_link',
    'Mixed Macro Link',
    'Macro-linked cyclicality features are incomplete, weak, or mixed.',
    100,
    '{"default":true}'::jsonb,
    '{"supportingFeatureKeys":["investmentRevenueSensitivity","investmentProfitSensitivity","corporateProfitSensitivity","gdpRevenueSensitivity"],"maxPresentedItems":4}'::jsonb,
    '{"minObservedMetricCount":1,"fullConfidenceMetricCount":1}'::jsonb
  )
ON CONFLICT (
  model_key,
  model_version,
  factor,
  axis,
  signal_key
)
DO UPDATE SET
  signal_label = EXCLUDED.signal_label,
  signal_description = EXCLUDED.signal_description,
  priority = EXCLUDED.priority,
  selection_rules = EXCLUDED.selection_rules,
  evidence_rules = EXCLUDED.evidence_rules,
  confidence_rules = EXCLUDED.confidence_rules,
  is_active = true,
  updated_at = now();
