-- Source of truth for factor axis display definitions.
-- Reapply this file to refresh factor/axis-level display metadata.

DROP TABLE IF EXISTS public.ticker_factor_axis_display_definitions;

CREATE TABLE public.ticker_factor_axis_display_definitions (
  id BIGSERIAL PRIMARY KEY,

  model_key TEXT NOT NULL,
  model_version TEXT NOT NULL,

  factor TEXT NOT NULL,
  axis TEXT NOT NULL,

  headline_title TEXT,
  axis_label TEXT,
  chart_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  baseline_labels JSONB NOT NULL DEFAULT '{}'::jsonb,
  display_payload JSONB NOT NULL DEFAULT '{}'::jsonb,

  display_order INTEGER NOT NULL DEFAULT 100,
  is_active BOOLEAN NOT NULL DEFAULT true,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT uq_tfadd UNIQUE (
    model_key,
    model_version,
    factor,
    axis
  ),

  CONSTRAINT chk_tfadd_chart_payload_object
  CHECK (jsonb_typeof(chart_payload) = 'object'),

  CONSTRAINT chk_tfadd_baseline_labels_object
  CHECK (jsonb_typeof(baseline_labels) = 'object'),

  CONSTRAINT chk_tfadd_display_payload_object
  CHECK (jsonb_typeof(display_payload) = 'object')
);

CREATE INDEX idx_tfadd_active_lookup
ON public.ticker_factor_axis_display_definitions (
  factor,
  axis,
  is_active
);

INSERT INTO public.ticker_factor_axis_display_definitions (
  model_key,
  model_version,
  factor,
  axis,
  headline_title,
  axis_label,
  chart_payload,
  baseline_labels,
  display_payload,
  display_order,
  is_active
)
VALUES
  ('factor_feature', 'v0', 'capex_cycle', 'fundamentals_based', 'CapEx Cycle', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"CapEx Cycle","chart":{"type":"timeseries"},"featureOrder":["capexInvestmentIntensityChange","capexTtmIncreaseValue","capexCycleAcceleration","capexCycleQuarterStretch","capexCycleAnnualStretch"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"capexInvestmentIntensityChange":"CapEx Intensity Change","capexTtmIncreaseValue":"CapEx TTM Increase","capexCycleAcceleration":"CapEx Acceleration","capexCycleQuarterStretch":"CapEx Quarter Stretch","capexCycleAnnualStretch":"CapEx Annual Stretch"}}'::jsonb, 1, true),
  ('factor_feature', 'v0', 'china_exposure', 'etf_exposure', NULL, 'ETF Exposure', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"ETF Exposure","featureLabels":{"chinaLargeCapBeta3Y":"3Y China Large-Cap ETF Beta","chinaInternetBeta3Y":"3Y China Internet ETF Beta","emergingMarketBeta3Y":"3Y Emerging Market ETF Beta"}}'::jsonb, 2, true),
  ('factor_feature', 'v0', 'commodity_linked', 'etf_exposure', NULL, 'ETF Exposure', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"ETF Exposure","featureLabels":{"broadCommodityBeta3Y":"3Y DBC Beta","goldBeta3Y":"3Y GLD Beta","silverBeta3Y":"3Y SLV Beta"}}'::jsonb, 3, true),
  ('factor_feature', 'v0', 'consumer_linked', 'etf_exposure', NULL, 'ETF Exposure', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"ETF Exposure","featureLabels":{"consumerDiscretionaryBeta3Y":"3Y XLY Beta","consumerStaplesBeta3Y":"3Y XLP Beta","retailBeta3Y":"3Y XRT Beta"}}'::jsonb, 4, true),
  ('factor_feature', 'v0', 'credit_sensitive', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"creditSpreadWideningRelativeReturn1Y":"1Y Credit-Spread Widening Return vs SPY","creditSpreadWideningRelativeReturn3Y":"3Y Credit-Spread Widening Return vs SPY","creditShockRelativeReturn1Y":"1Y Credit-Shock Return vs SPY","highYieldSpreadBeta3Y":"3Y High-Yield Spread Beta per 100bp","investmentGradeSpreadBeta3Y":"3Y Investment-Grade Spread Beta per 100bp"}}'::jsonb, 5, true),
  ('factor_feature', 'v0', 'defensive', 'fundamentals_based', 'Defensive', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"Defensive","chart":{"type":"timeseries"},"featureOrder":["defensiveStability","defensiveBufferPosition","defensiveShockAbsorption","defensiveBurdenRelief","defensiveBurdenTrendRelief","defensiveBurdenContractionConsistency"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"defensiveStability":"Defensive Stability","defensiveBufferPosition":"Defensive Buffer Position","defensiveShockAbsorption":"Shock Absorption","defensiveBurdenRelief":"Burden Relief","defensiveBurdenTrendRelief":"Burden Trend Relief","defensiveBurdenContractionConsistency":"Burden Contraction Consistency"}}'::jsonb, 6, true),
  ('factor_feature', 'v0', 'defensive', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"downMarketDefense1Y":"1Y Down Market Defense","downMarketDefense3Y":"3Y Down Market Defense","volatilityStressDefense1Y":"1Y Volatility Stress Defense","volatilityStressDefense3Y":"3Y Volatility Stress Defense","drawdownDefense1Y":"1Y Drawdown Defense","downsideCaptureDefense1Y":"1Y Downside Capture Defense"}}'::jsonb, 7, true),
  ('factor_feature', 'v0', 'duration_sensitive', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"shortRateBeta3Y":"3Y 2Y-Rate Beta per 100bp","intermediateRateBeta3Y":"3Y 5Y-Rate Beta per 100bp","ultraLongRateBeta3Y":"3Y 30Y-Rate Beta per 100bp","yieldCurveBeta3Y":"3Y 10Y-2Y Curve Beta per 100bp","shortTreasuryBeta3Y":"3Y SHY Beta","intermediateTreasuryBeta3Y":"3Y IEF Beta","longBondBeta3Y":"3Y TLT Beta"}}'::jsonb, 8, true),
  ('factor_feature', 'v0', 'energy_linked', 'etf_exposure', NULL, 'ETF Exposure', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"ETF Exposure","featureLabels":{"energySectorBeta3Y":"3Y XLE Beta","energyExplorationBeta3Y":"3Y XOP Beta","oilServicesBeta3Y":"3Y OIH Beta"}}'::jsonb, 9, true),
  ('factor_feature', 'v0', 'energy_linked', 'fundamentals_based', 'Energy Linked', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile"}'::jsonb, '{"headlineTitle":"Energy Linked","chart":{"type":"timeseries"},"featureOrder":["energyActivityGrowth","energyActivityAcceleration","energyActivityStretch","energyAssetInventoryGrowth","energyAssetInventoryAcceleration","energyAssetInventoryStretch","energyCostPressure","energyCostAcceleration","energyCostStretch"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile"},"featureLabels":{"energyActivityGrowth":"Energy Activity Growth","energyActivityAcceleration":"Energy Activity Acceleration","energyActivityStretch":"Energy Activity Stretch","energyAssetInventoryGrowth":"Energy Asset & Inventory Growth","energyAssetInventoryAcceleration":"Energy Asset & Inventory Acceleration","energyAssetInventoryStretch":"Energy Asset & Inventory Stretch","energyCostPressure":"Energy Cost Pressure","energyCostAcceleration":"Energy Cost Acceleration","energyCostStretch":"Energy Cost Stretch"}}'::jsonb, 10, true),
  ('factor_feature', 'v0', 'growth', 'fundamentals_based', 'Growth', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"Growth","chart":{"type":"timeseries"},"featureOrder":["latestGrowth","durableGrowth","yoyGrowthAcceleration","turnaroundMomentum"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"latestGrowth":"Latest YoY Growth","durableGrowth":"TTM YoY Growth","yoyGrowthAcceleration":"YoY Growth Acceleration","turnaroundMomentum":"Turnaround Momentum"}}'::jsonb, 11, true),
  ('factor_feature', 'v0', 'growth', 'valuation', 'Growth Valuation', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"Growth Valuation","chart":{"type":"timeseries"},"featureOrder":["priceToDilutedTtmEps","priceToBasicTtmEps","dilutedTtmEpsGrowth","basicTtmEpsGrowth"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"priceToDilutedTtmEps":"Price to Diluted TTM EPS","priceToBasicTtmEps":"Price to Basic TTM EPS","dilutedTtmEpsGrowth":"Diluted TTM EPS Growth","basicTtmEpsGrowth":"Basic TTM EPS Growth"}}'::jsonb, 12, true),
  ('factor_feature', 'v0', 'high_beta', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"marketBeta1Y":"1Y Market Beta","marketBeta3Y":"3Y Market Beta","correlationToMarket3Y":"3Y Market Correlation","upsideCapture1Y":"1Y Upside Capture","downsideCapture1Y":"1Y Downside Capture","qqqBeta1Y":"1Y QQQ Beta","qqqBeta3Y":"3Y QQQ Beta","qqqCorrelation3Y":"3Y QQQ Correlation","diaBeta1Y":"1Y DIA Beta","diaBeta3Y":"3Y DIA Beta","diaCorrelation3Y":"3Y DIA Correlation"}}'::jsonb, 13, true),
  ('factor_feature', 'v0', 'income', 'fundamentals_based', 'Income', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"Income","chart":{"type":"timeseries"},"featureOrder":["dividendConsistency","dividendPosition","dividendMomentum","dividendCoverageRatio","dividendPayoutRatio","shareCountReduction"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"dividendConsistency":"Dividend Consistency","dividendPosition":"Dividend Position","dividendMomentum":"Dividend Momentum","dividendCoverageRatio":"Dividend Coverage","dividendPayoutRatio":"Dividend Payout Ratio","shareCountReduction":"Share Count Reduction"}}'::jsonb, 14, true),
  ('factor_feature', 'v0', 'income', 'valuation', 'Income Valuation', NULL, '{"type":"timeseries"}'::jsonb, '{}'::jsonb, '{"headlineTitle":"Income Valuation","chart":{"type":"timeseries"},"featureOrder":["dividendYield","buybackYield","shareholderYield","dividendYieldShare","buybackYieldShare"],"featureLabels":{"dividendYield":"Dividend Yield","buybackYield":"Buyback Yield","shareholderYield":"Shareholder Yield","dividendYieldShare":"Dividend Yield Share","buybackYieldShare":"Buyback Yield Share"}}'::jsonb, 15, true),
  ('factor_feature', 'v0', 'inflation_hedge', 'etf_exposure', NULL, 'ETF Exposure', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"ETF Exposure","featureLabels":{"inflationHedgeBasketBeta3Y":"3Y Inflation-Hedge Basket Beta"}}'::jsonb, 16, true),
  ('factor_feature', 'v0', 'liquidity_sensitive', 'fundamentals_based', 'Liquidity Sensitive', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile"}'::jsonb, '{"headlineTitle":"Liquidity Sensitive","chart":{"type":"timeseries"},"featureOrder":["receivablesChange","receivablesBuild","receivablesToRevenue","inventoryChange","inventoryBuild","inventoryToRevenue","payablesChange","payablesBuild","payablesToRevenue"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile"},"featureLabels":{"receivablesChange":"Receivables Change","receivablesBuild":"Receivables Build","receivablesToRevenue":"Receivables to Revenue","inventoryChange":"Inventory Change","inventoryBuild":"Inventory Build","inventoryToRevenue":"Inventory to Revenue","payablesChange":"Payables Change","payablesBuild":"Payables Build","payablesToRevenue":"Payables to Revenue"}}'::jsonb, 17, true),
  ('factor_feature', 'v0', 'low_volatility', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"realizedVolatility1Y":"1Y Realized Volatility","realizedVolatility3Y":"3Y Realized Volatility","downsideVolatility1Y":"1Y Downside Volatility","maxDrawdown1Y":"1Y Max Drawdown"}}'::jsonb, 18, true),
  ('factor_feature', 'v0', 'momentum', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"priceReturn3M":"3M Price Return","priceReturn6M":"6M Price Return","priceReturn12M":"12M Price Return","priceMomentum12MEx1M":"12M Momentum ex 1M","relativeReturn3M":"3M Return vs SPY","relativeReturn6M":"6M Return vs SPY","relativeReturn12M":"12M Return vs SPY","relativeMomentum12MEx1M":"12M Momentum ex 1M vs SPY","momentumConsistency12M":"12M Momentum Consistency","distanceFrom52WeekHigh":"Distance From 52W High"}}'::jsonb, 19, true),
  ('factor_feature', 'v0', 'quality', 'fundamentals_based', 'Quality', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"Quality","chart":{"type":"timeseries"},"featureOrder":["profitabilityConsistency","profitabilityPosition","profitabilityTurnaround","cashEarningsCoverage","accrualsToAssets","grossProfitToAssets","operatingReturnOnAssets","netIncomeReturnOnAssets"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"profitabilityConsistency":"Profitability Consistency","profitabilityPosition":"Profitability Position","profitabilityTurnaround":"Profitability Turnaround","cashEarningsCoverage":"Cash Earnings Coverage","accrualsToAssets":"Accruals to Assets","grossProfitToAssets":"Gross Profit to Assets","operatingReturnOnAssets":"Operating Return on Assets","netIncomeReturnOnAssets":"Net Income Return on Assets"}}'::jsonb, 20, true),
  ('factor_feature', 'v0', 'rate_sensitive', 'fundamentals_based', 'Rate Sensitive', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile"}'::jsonb, '{"headlineTitle":"Rate Sensitive","chart":{"type":"timeseries"},"featureOrder":["rateGrossInterestToOperatingIncome","rateGrossInterestToOperatingCashFlow","rateInterestExpenseGrowth","rateInterestIncomeToOperatingCashFlow","rateInterestIncomeToInterestExpense","rateInterestIncomeGrowth","rateNetInterestToOperatingCashFlow","rateNetInterestToOperatingIncome","rateNetInterestGrowth","rateShortTermDebtToAssets","rateShortTermDebtShare","rateTotalDebtToAssets","rateCashToTotalDebt","rateCashInvestmentsToTotalDebt","rateCashInvestmentsToInterestExpense"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile"},"featureLabels":{"rateGrossInterestToOperatingIncome":"Interest Expense to Operating Income","rateGrossInterestToOperatingCashFlow":"Interest Expense to Operating Cash Flow","rateInterestExpenseGrowth":"Interest Expense Growth","rateInterestIncomeToOperatingCashFlow":"Interest Income to Operating Cash Flow","rateInterestIncomeToInterestExpense":"Interest Income to Interest Expense","rateInterestIncomeGrowth":"Interest Income Growth","rateNetInterestToOperatingCashFlow":"Net Interest to Operating Cash Flow","rateNetInterestToOperatingIncome":"Net Interest to Operating Income","rateNetInterestGrowth":"Net Interest Growth","rateLongTermDebtPosition":"Long-Term Debt Position","rateShortTermDebtToAssets":"Short-Term Debt to Assets","rateShortTermDebtShare":"Short-Term Debt Share","rateShortTermDebtPosition":"Short-Term Debt Position","rateTotalDebtToAssets":"Total Debt to Assets","rateTotalDebtPosition":"Total Debt Position","rateCashToLongTermDebt":"Cash to Long-Term Debt","rateCashToTotalDebt":"Cash to Total Debt","rateCashInvestmentsToAssets":"Cash & Investments to Assets","rateCashInvestmentsToTotalDebt":"Cash & Investments to Total Debt","rateCashInvestmentsToInterestExpense":"Cash & Investments to Interest Expense"}}'::jsonb, 21, true),
  ('factor_feature', 'v0', 'rate_sensitive', 'market_price', NULL, 'Market Price', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"Market Price","featureLabels":{"rateUpRelativeReturn1Y":"1Y Rate-Up Return vs SPY","rateUpRelativeReturn3Y":"3Y Rate-Up Return vs SPY","rateShockRelativeReturn1Y":"1Y Rate-Shock Return vs SPY","rateBeta3Y":"3Y 10Y-Rate Beta per 100bp","curveFlatteningRelativeReturn3Y":"3Y Curve-Flattening Return vs SPY"}}'::jsonb, 22, true),
  ('factor_feature', 'v0', 'reshoring_defense', 'etf_exposure', NULL, 'ETF Exposure', '{}'::jsonb, '{}'::jsonb, '{"axisLabel":"ETF Exposure","featureLabels":{"aerospaceDefenseBeta3Y":"3Y Aerospace & Defense ETF Beta","infrastructureBeta3Y":"3Y Infrastructure ETF Beta","powerGridBeta3Y":"3Y Power Grid ETF Beta"}}'::jsonb, 23, true),
  ('factor_feature', 'v0', 'size', 'valuation', 'Size Valuation', NULL, '{"type":"timeseries"}'::jsonb, '{}'::jsonb, '{"headlineTitle":"Size Valuation","chart":{"type":"timeseries"},"featureOrder":["marketCapitalization","logMarketCapitalization"],"featureLabels":{"marketCapitalization":"Market Capitalization","logMarketCapitalization":"Log Market Capitalization"}}'::jsonb, 24, true),
  ('factor_feature', 'v0', 'value', 'fundamentals_based', 'Value', NULL, '{"type":"timeseries"}'::jsonb, '{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"}'::jsonb, '{"headlineTitle":"Value","chart":{"type":"timeseries"},"featureOrder":["bookEquityToAssets","bookEquityGrowth","bookEquityPosition","retainedEarningsToAssets","cashToAssets","liabilitiesToAssets","debtToAssets","assetBaseGrowth","assetBasePosition"],"baselineLabels":{"sectorPercentile":"Sector Percentile","sp500Percentile":"S&P 500 Percentile","excessVsUsNominalGdp":"Excess vs US Nominal GDP"},"featureLabels":{"bookEquityToAssets":"Book Equity to Assets","bookEquityGrowth":"Book Equity Growth","bookEquityPosition":"Book Equity Position","retainedEarningsToAssets":"Retained Earnings to Assets","cashToAssets":"Cash to Assets","liabilitiesToAssets":"Liabilities to Assets","debtToAssets":"Long-Term Debt to Assets","assetBaseGrowth":"Asset Base Growth","assetBasePosition":"Asset Base Position"}}'::jsonb, 25, true),
  ('factor_feature', 'v0', 'value', 'valuation', 'Value Valuation', NULL, '{"type":"timeseries"}'::jsonb, '{}'::jsonb, '{"headlineTitle":"Value Valuation","chart":{"type":"timeseries"},"featureOrder":["priceToBook","priceToSales","enterpriseValueToSales","priceToEarnings","priceToOperatingCashFlow","freeCashFlowYield"],"featureLabels":{"priceToBook":"Price to Book","priceToSales":"Price to Sales","enterpriseValueToSales":"Enterprise Value to Sales","priceToEarnings":"Price to Earnings","priceToOperatingCashFlow":"Price to Operating Cash Flow","freeCashFlowYield":"Free Cash Flow Yield"}}'::jsonb, 26, true),
  ('factor_feature', 'v0', 'cyclical', 'macro_linked', 'Cyclical Macro Link', 'Macro Linked', '{"type":"timeseries"}'::jsonb, '{"macroBeta":"Macro Sensitivity Beta"}'::jsonb, '{"headlineTitle":"Cyclical Macro Link","axisLabel":"Macro Linked","chart":{"type":"timeseries"},"featureOrder":["investmentRevenueSensitivity","investmentProfitSensitivity","corporateProfitSensitivity","gdpRevenueSensitivity"],"baselineLabels":{"macroBeta":"Macro Sensitivity Beta"},"featureLabels":{"investmentRevenueSensitivity":"Investment Revenue Sensitivity","investmentProfitSensitivity":"Investment Profit Sensitivity","corporateProfitSensitivity":"Corporate Profit Sensitivity","gdpRevenueSensitivity":"GDP Revenue Sensitivity"}}'::jsonb, 27, true);
